### ISSUE TITLE
怎么启用集成响应？

### ISSUE THREAD

**Issue by zhuangdx** [tencentyun/serverless-tencent-scf#2]
你好，这边需要通过云函数返回一个html页面，参考已有的例子，需要在云api触发事件中启用集成响应，但我没有在配置说明找到这个参数如何配置，请问该怎么做？谢谢
```
events:
      - apigw:
          name: SCF_API_demo
          parameters:
            protocols:
              - http
            serviceName: serverless
            environment: release
            endpoints:
              - path: /demo
                method: ANY
```
