### ISSUE TITLE
Error: The value specified in the parameter Handler is not valid.

### ISSUE THREAD

**Issue by M09Ic** [tencentyun/serverless-tencent-scf#4]
```Uploading service to cos[sls-cloudfunction-ap-shanghai].
Uploaded service successful 
Creating function test-dev-test
ErrorCode: InvalidParameterValue.Handler RequestId: ***
Error: The value specified in the parameter Handler is not valid. Please fix it and try again. Reference: https://mc.tencent.com/s2W2vZ0i
    at ScfClient.parseResponse (.\node_modules\tencentcloud-sdk-nodejs\tencentcloud\common\abstract_client.js:138:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ScfClient.doRequest (.\node_modules\tencentcloud-sdk-nodejs\tencentcloud\common\abstract_client.js:100:16)
```

按照官方文档提供的写法, 独立打包每个目录.

serverless.yml
```
package:
  individually: true
  patterns:
    - "!**/*"

plugins:
  - serverless-tencent-scf

functions:
  test:
    handler: test/wsgi.handler
    memorySize: 256
    timeout: 600
    package:
      patterns:
        - "test/**"
```

deploy发生了如上报错. 似乎是腾讯云函数不支持入口点不在根目录的zip? 

handler 去掉嵌套就能正常部署, 但是有多个函数的时候每个函数一个配置文件太过麻烦. 是否能支持类似aws的部署?
